# Generated by Django 5.0.2 on 2024-03-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название контракта')),
                ('document', models.FileField(upload_to='contracts/documents', verbose_name='Документ')),
                ('date_signed', models.DateField(verbose_name='Дата заключения')),
                ('validity_period', models.DateField(verbose_name='Период окончания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='products.product', verbose_name='Предоставляемая услуга')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
