# Generated by Django 5.0.2 on 2024-03-24 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Фамилия и имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество (при наличии)')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Формат номера телефона должен быть: +79999999999 или 89999999999', regex='^((8|\\+7|)(\\d{10}))$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='advertising.advertisingcompany', verbose_name='Рекламная компания')),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
            },
        ),
    ]
