# Generated by Django 5.0.2 on 2024-03-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='advertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='advertising.advertisingcompany', verbose_name='Рекламная компания'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия и имя'),
        ),
    ]
